# This is a basic workflow to help you get started with Actions

name: Docker image creation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lbroedersc1b/c1bpoc:${GITHUB_SHA}
      - name: Push the tagged Docker image
        run: docker push lbroedersc1b/c1bpoc:${GITHUB_SHA}
